<div class="kontainer">
    <header>
        <h1>Min enkla blogg</h1>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="index.php">Hemsida</a></li>
                <li class="nav-item"><a class="nav-link" href="skriva.php">Skriva inlägg</a></li>
                <li class="nav-item"><a class="nav-link" href="lasa.php">Läsa inlägg</a></li>
            </ul>
        </nav>
    </header>